apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasks-backend.fullname" . }}
  labels:
  {{- include "tasks-backend.labels" . | nindent 4 }}
data:
  application.yml: |
    logging:
      level:
        org.springframework.web: {{ .Values.logging.level }}
        de.progeek.tasks: {{ .Values.logging.level }}
  MONGODB_DATABASE: {{ .Values.mongodb.auth.database }}
  MONGODB_PORT: {{ .Values.mongodb.service.port | quote }}
  MONGODB_HOST: {{ include "tasks-backend.mongodb.fullname" . }}
