{{- if and .Values.ingress.enabled ( or .Values.backend.enabled ) -}}
{{- $fullName := include "tasks-backend.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "tasks-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tasks-backend.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          {{- end }}

  {{- end }}
