apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tasks-backend.fullname" . }}
  labels:
  {{- include "tasks-backend.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_USERNAME: {{ .Values.mongodb.auth.username | b64enc | quote }}
  MONGODB_PASSWORT: {{ .Values.mongodb.auth.password | b64enc | quote }}
