version: "3"
services:
  mongodb:
    image: bitnami/mongodb:5.0
    environment:
      MONGODB_DATABASE: tasks
      MONGODB_USERNAME: tasks
      MONGODB_PASSWORD: pahshu4aiChi7Ega
      MONGODB_ROOT_PASSWORD: pahshu4aiChi7Ega
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  tasks-backend:
    image: ghcr.io/hsfl-webapps-react-ts-ss22/tasks-backend:1.2.0
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: tasks
      MONGODB_PASSWORD: pahshu4aiChi7Ega
      MONGODB_DATABASE: tasks
    ports:
      - 8080:8080
volumes:
  mongodb_data:
