spring:
  data:
    mongodb:
      username: tasks
      password: pahshu4aiChi7Ega
      database: tasks
      port: 27017
      host: localhost
logging:
  level:
    org.springframework.web: DEBUG
    de.progeek.tasks: DEBUG

